categories:
  咨询:
    - 管理咨询
    - 咨询服务
    - 管理提升
    - 管理诊断
    - 流程管理
    - 流程优化
    - 流程制度
    - 企业文化
    - 薪酬
    - 绩效
    - 定岗定编
    - 岗位价值评估
    - 组织管控
    - 激励机制
    - 人力资源
  培训:
    - 入库服务
    - 入围服务
    - 赋能
    - 培训服务
    - 培训供应商
    - 政企服务
    - 管理能力
    - 胜任力
    - 素质提升
    - 内训师
    - AI赋能
    - 团队拓展
    - 新员工入职培训
    - 能力提升
    - 素质提升
  绩效系统:
    - 绩效软件
    - 绩效平台
    - 绩效考核
    - 绩效管理
    - 绩效系统
    - 绩效管理信息系统

blacklist:
  绩效系统:
    - 银行 绩效
    - 医院 绩效
    - 医疗
    - 诊所 绩效
